/*
 * Module 2 Practice Assessment - Task Tracker utilities (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs check the functions you implement in src/app.js.
 * 10 specs x 2 marks = 20.
 *
 * DO NOT EDIT THIS FILE. Make every spec turn green.
 * ------------------------------------------------------------------
 */

describe("Module 2 Practice Assessment - Task Tracker utilities", function () {

  function tasks() {
    return [
      { title: "Buy milk",        status: "todo", done: false, priority: "high" },
      { title: "Write the essay", status: "todo", done: false, priority: "low"  },
      { title: "Ship",            status: "done", done: true,  priority: "low"  }
    ];
  }

  // 1 --------------------------------------------------------------
  it("1. greet(name) returns a template-literal greeting", function () {
    expect(greet("Aisha")).toBe("Hi, Aisha! Welcome back.");
    expect(greet("Ravi")).toBe("Hi, Ravi! Welcome back.");
  });

  // 2 --------------------------------------------------------------
  it("2. isPassing(score) is true only for scores >= 40", function () {
    expect(isPassing(40)).toBe(true);
    expect(isPassing(95)).toBe(true);
    expect(isPassing(39)).toBe(false);
    expect(isPassing(0)).toBe(false);
  });

  // 3 --------------------------------------------------------------
  it("3. sumScores(scores) adds up the array (0 when empty)", function () {
    expect(sumScores([10, 20, 30])).toBe(60);
    expect(sumScores([5])).toBe(5);
    expect(sumScores([])).toBe(0);
  });

  // 4 --------------------------------------------------------------
  it("4. highScores(scores, min) keeps only scores above min", function () {
    expect(highScores([10, 50, 90], 40)).toEqual([50, 90]);
    expect(highScores([10, 20], 40)).toEqual([]);
    // original array must be untouched
    var src = [10, 50, 90];
    highScores(src, 40);
    expect(src).toEqual([10, 50, 90]);
  });

  // 5 --------------------------------------------------------------
  it("5. titles(tasks) maps each task to its title", function () {
    expect(titles(tasks())).toEqual(["Buy milk", "Write the essay", "Ship"]);
    expect(titles([])).toEqual([]);
  });

  // 6 --------------------------------------------------------------
  it("6. countByStatus(tasks, status) counts matching tasks", function () {
    expect(countByStatus(tasks(), "todo")).toBe(2);
    expect(countByStatus(tasks(), "done")).toBe(1);
    expect(countByStatus(tasks(), "archived")).toBe(0);
  });

  // 7 --------------------------------------------------------------
  it("7. toggleDone(task) returns a NEW object with done flipped", function () {
    var t = { title: "Buy milk", done: false, priority: "high" };
    var out = toggleDone(t);
    expect(out.done).toBe(true);
    expect(out.title).toBe("Buy milk");
    expect(out.priority).toBe("high");
    // must not mutate the original
    expect(t.done).toBe(false);
    expect(out).not.toBe(t);
  });

  // 8 --------------------------------------------------------------
  it("8. longestTitle(tasks) returns the longest title string", function () {
    expect(longestTitle(tasks())).toBe("Write the essay");
    expect(longestTitle([{ title: "Only one" }])).toBe("Only one");
  });

  // 9 --------------------------------------------------------------
  it("9. averageScore(scores) averages (0 for empty array)", function () {
    expect(averageScore([10, 20, 30])).toBe(20);
    expect(averageScore([4, 5])).toBe(4.5);
    expect(averageScore([])).toBe(0);
  });

  // 10 -------------------------------------------------------------
  it("10. formatTask(task) builds a template-literal display line", function () {
    expect(formatTask({ title: "Ship", done: true, priority: "low" }))
      .toBe("[x] Ship (low)");
    expect(formatTask({ title: "Buy milk", done: false, priority: "high" }))
      .toBe("[ ] Buy milk (high)");
  });

});
