/*
 * TuneFetch — automated tests (Jasmine)
 * ------------------------------------------------------------------
 * These 10 specs run INSIDE index.html and check the async behaviour
 * you build in src/app.js: creating Promises, resolving/rejecting,
 * async/await, fetching + parsing JSON, error handling, and Promise.all.
 * Every spec fails right now — make them pass by completing src/app.js.
 *
 * There is NO real network here. Each spec installs a FAKE global
 * `fetch` (see mockFetch below) that returns canned responses, so your
 * functions must call the global `fetch(url)` exactly like the real one:
 *   - `await fetch(url)` gives a response object with `.ok`, `.status`
 *     and a `.json()` method that returns a Promise of the parsed data.
 *
 * DO NOT EDIT THIS FILE. Only edit src/app.js.
 * ------------------------------------------------------------------
 */

describe("TuneFetch", function () {

  // The canned playlist the fake API serves at "/api/songs".
  var SONGS = [
    { id: 1, title: "Levitating",      artist: "Dua Lipa",    plays: 120 },
    { id: 2, title: "Blinding Lights",  artist: "The Weeknd",  plays: 200 },
    { id: 3, title: "As It Was",        artist: "Harry Styles", plays: 150 }
  ];

  var realFetch;

  // Install a fake `fetch`. `routes` maps a url -> { data, ok, status }.
  // An unknown url rejects, exactly like a real network failure would.
  function mockFetch(routes) {
    window.fetch = function (url) {
      var route = routes[url];
      if (!route) {
        return Promise.reject(new TypeError("Failed to fetch: " + url));
      }
      return Promise.resolve({
        ok: route.ok !== false,
        status: route.status || 200,
        json: function () { return Promise.resolve(route.data); }
      });
    };
  }

  beforeEach(function () {
    realFetch = window.fetch;
    // sensible default: /api/songs returns the playlist, 200 OK
    mockFetch({ "/api/songs": { data: SONGS, ok: true, status: 200 } });
  });

  afterEach(function () {
    window.fetch = realFetch;
  });

  it("1. resolveWith(value) returns a Promise that resolves to value", function () {
    var p = resolveWith(42);
    expect(typeof p.then).toBe("function"); // it is a Promise / thenable
    return p.then(function (v) { expect(v).toBe(42); });
  });

  it("2. rejectWith(message) returns a Promise that rejects with an Error", function () {
    return rejectWith("boom").then(
      function () { fail("expected the promise to reject"); },
      function (err) {
        expect(err instanceof Error).toBe(true);
        expect(err.message).toBe("boom");
      }
    );
  });

  it("3. delay(ms) returns a Promise that resolves after the delay", function () {
    var done = false;
    var p = delay(20);
    expect(typeof p.then).toBe("function");
    expect(done).toBe(false); // hasn't resolved synchronously
    return p.then(function () { done = true; expect(done).toBe(true); });
  });

  it("4. doubleAsync(n) is async and resolves to n * 2", function () {
    var p = doubleAsync(8);
    expect(typeof p.then).toBe("function"); // async functions return a Promise
    return p.then(function (v) { expect(v).toBe(16); });
  });

  it("5. fetchJSON(url) fetches the url and returns the parsed JSON", function () {
    return fetchJSON("/api/songs").then(function (data) {
      expect(data).toEqual(SONGS);
    });
  });

  it("6. fetchJSON(url) throws/rejects when response.ok is false", function () {
    mockFetch({ "/api/songs": { data: null, ok: false, status: 500 } });
    return fetchJSON("/api/songs").then(
      function () { fail("expected fetchJSON to reject on a non-ok response"); },
      function (err) { expect(err instanceof Error).toBe(true); }
    );
  });

  it("7. getSongTitles(url) resolves to an array of every song title", function () {
    return getSongTitles("/api/songs").then(function (titles) {
      expect(titles).toEqual(["Levitating", "Blinding Lights", "As It Was"]);
    });
  });

  it("8. getSongById(url, id) resolves to the matching song, or null", function () {
    return getSongById("/api/songs", 2).then(function (song) {
      expect(song).toEqual({ id: 2, title: "Blinding Lights", artist: "The Weeknd", plays: 200 });
      return getSongById("/api/songs", 999);
    }).then(function (missing) {
      expect(missing).toBe(null);
    });
  });

  it("9. fetchAll(urls) uses Promise.all to resolve to an array of all results", function () {
    mockFetch({
      "/api/a": { data: { ok: "a" } },
      "/api/b": { data: { ok: "b" } }
    });
    return fetchAll(["/api/a", "/api/b"]).then(function (results) {
      expect(results).toEqual([{ ok: "a" }, { ok: "b" }]);
    });
  });

  it("10. safeFetch(url) resolves to the data on success, or null on failure", function () {
    return safeFetch("/api/songs").then(function (data) {
      expect(data).toEqual(SONGS);
      return safeFetch("/api/does-not-exist"); // unknown url -> fetch rejects
    }).then(function (result) {
      expect(result).toBe(null);
    });
  });

});
